version: '3'
services:
  frontend:
    build:
      context: ./DeltaLMS
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Maps port 80 in the container to port 3000 on your machine
    depends_on:
      - backend

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Maps port 5000 in the container to port 5000 on your machine
    environment:
      - NODE_ENV=production
